# **Diplomado IA: Aprendizaje Profundo I - Parte 1**. <br> Práctico Clase 7: PyTorch
---
---

**Profesores:**
- Alain Raymond
- Gabriel Sepúlveda
- Miguel Fadic
- Álvaro Soto

**Ayudante:**
- Andrés Villa
---
---

El siguiente práctico se debe realizar de forma individual. El formato de entregar es el **archivo .ipynb con todas las celdas ejecutadas**. Las secciones donde se planteen preguntas de forma explícita, deben ser respondida en celdas de texto, y no se aceptará solo el _output_ de una celda de código como respuesta.

**Nombre alumno:**

El siguiente práctico contendrá 1 o más actividades a realizar. Algunas actividades corresponderán a escribir código y otras a responder preguntas.

Antes de responder, se recomienda **fuertemente** revisar las secciones previas donde se desarrollan los ejemplos, dado que algunas de las actividades pueden ser completadas reutilizando el mismo código.


---
**IMPORTANTE:** habrá un bonus de 1 décima para todos aquellos alumnos/as que muestren buen orden en sus respuestas (esto aplica a legibilidad de código, buena redacción, formalidad, organización del jupyter notebook, seguimiento de instrucciones, etc). El criterio lo pondrá cada ayudante corrector. La nota máxima obtenible en el laboratorio es 7.0

## El Tensor: la unidad fundamental.

Los tensores son el elemento fundamental con que trabajarán nuestras redes profundas. Un tensor es simplemente una matriz de n-dimensiones.

* En **imágenes**, usamos tensores de 4 dimensiones: 3 dimensiones (alto, ancho y color) más una cuarta dimensión asociada a los elementos del batch.

* Cuando trabajamos con **texto** podemos tener tensores en 3 dimensiones (dimensión de embedding, palabras y batch).

* Si trabajamos con **videos** tenemos que agregar otra dimensión para el tiempo. En fin, todos estos datos distintos al final se representan como matrices de números en 3, 4 ó 5 dimensiones distintas.

Pytorch representa los tensores via la clase torch.Tensor. Todas las redes neuronales que hagamos requieren tensores para poder trabajar. Nuestros datasets no servirán de nada si no podemos transformarlos en tensores que podamos ocupar con nuestras redes. Si han trabajado con *ndarray* de Numpy la forma de ocuparlos es muy similar. Veamos un tensor de ejemplo de 3 dimensiones: ancho, alto y batch.

In [ ]:
import torch

batch_dim = 2
ancho = 4
alto = 3
tensor_ejemplo = torch.randn((batch_dim, ancho, alto)).float() # Tensor aleatorio
print("El tensor es: {}\n".format(tensor_ejemplo))
print("La forma del tensor es: {}".format(tensor_ejemplo.shape))
print("El tipo del tensor es: {}".format(type(tensor_ejemplo)))

El tensor es: tensor([[[-1.3720, -1.8633, -0.3897],
         [ 1.4652,  0.5606, -1.4053],
         [-0.9364, -0.7118, -0.9043],
         [-1.2584, -0.1782, -0.3589]],

        [[-2.5879, -0.4404, -0.2003],
         [-1.0105,  0.1043,  1.1194],
         [ 1.8713,  0.2288,  0.1374],
         [ 0.3063, -0.2874,  1.3219]]])

La forma del tensor es: torch.Size([2, 4, 3])
El tipo del tensor es: <class 'torch.Tensor'>


Crear un tensor desde un arreglo de Python es sencillo:

In [ ]:
arreglo = [[1, 2, 3], [4, 5, 6]]
tensor_desde_arreglo = torch.tensor(arreglo)
print(tensor_desde_arreglo, tensor_desde_arreglo.shape)
tensor_desde_arreglo2 = torch.tensor(arreglo)
suma = tensor_desde_arreglo +  tensor_desde_arreglo2
print(suma)

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
tensor([[ 2,  4,  6],
        [ 8, 10, 12]])


Uno trabaja los tensores de la misma manera que cualquier otra variable numérica en Python. Se pueden, sumar y restar sin problema. La multiplicación por escalares no supone problema y la multiplicación de tensores también está soportada.



In [ ]:
tensor_1 = torch.randn((10,2,3))
tensor_2 = torch.randn((10,2,3))

tensor_3 = tensor_1*tensor_2
print(tensor_1.shape)
print(tensor_2)
print(tensor_3)

torch.Size([10, 2, 3])
tensor([[[ 0.2331, -1.6168,  0.3986],
         [-0.7025, -1.8639,  1.8725]],

        [[-0.8412, -1.8290, -0.5981],
         [-1.5516, -0.3071,  0.7993]],

        [[-0.9435, -0.0841, -0.2522],
         [-0.2744, -1.1001,  0.9234]],

        [[ 3.2774, -0.6224,  0.1349],
         [ 0.5764, -0.8497,  0.0551]],

        [[-0.1698, -1.2902, -0.5799],
         [ 1.5215,  0.3394,  1.9947]],

        [[ 0.2495, -1.3233,  1.0862],
         [ 0.9773, -0.5932,  2.3610]],

        [[-1.6675,  1.0963, -0.4758],
         [ 0.6394, -0.4209,  1.0465]],

        [[ 0.5397, -1.3389,  1.5444],
         [ 1.0511,  0.0260,  1.0050]],

        [[ 0.1433, -0.1158, -1.5016],
         [-0.4064,  0.2188, -0.8516]],

        [[ 1.7507,  0.1611,  0.1199],
         [-0.2061, -0.6463, -0.1771]]])
tensor([[[-5.0415e-01, -1.2882e+00, -7.1178e-02],
         [ 2.3743e-01, -1.6097e+00,  1.1153e+00]],

        [[ 4.7991e-01,  1.0099e+00,  2.0264e-01],
         [-1.8562e+00,  5.1635e-01, -1.0445e+

Podemos indexarlos:

In [ ]:
print(tensor_1.shape)

lista = [1, 2, 3,4]

print(lista[0:2])

tensor_indexado = tensor_1[0:2,0,0]
print(tensor_indexado, tensor_indexado.shape)

torch.Size([10, 2, 3])
[1, 2]
tensor([-2.1632, -0.5705]) torch.Size([2])


In [ ]:
torch.randn(10, 3, 64, 64).shape

torch.Size([10, 3, 64, 64])

#### Sobre la dimensión batch

La dimensión de batch es importante pues es la que nos permite poder entrenar de forma paralela en nuestras GPUs. El estándar de Pytorch es que ésta es la primera dimensión de nuestros tensores siempre. Aunque solo evaluar un elemento en nuestra red, este debe tener una dimensión de batch en su primer lugar o sino no funcionará. También es necesario mencionar que Pytorch espera siempre que la dimensión del canal vaya antes que las dimensiones de ancho y alto en imágenes.

### Sobre el dispositivo asociado

Los tensores son procesados por la CPU o por una GPU. Como quizás hemos escuchado antes, sabemos que parte de la explosión de Deep Learning viene por la disponibilidad de GPUs cada vez más poderosas. Para poder trabajar en GPU un tensor tenemos que hacer lo siguiente:

In [ ]:
tensor_nuevo = torch.randn((1,2,3))     # Por defecto el tensor está en CPU
tensor_nuevo_gpu = tensor_nuevo.cuda()  # Creé una copia de tensor_nuevo en GPU!
otra_forma = tensor_nuevo.to("cuda")    # Creé otra copia de tensor_nuevo en GPU!
print(otra_forma)


tensor([[[ 0.3019,  1.3206, -0.5961],
         [-0.6800, -0.2182, -1.8108]]], device='cuda:0')


## Definición del Modelo
Como vimos en el laboratorio pasado, definir un modelo de aprendizaje profundo consiste en definir una nueva clase que herede de torch.nn.Module.

Esta clase debe implementar dos métodos para funcionar como un modelo válido en Pytorch:

* Método \_\_init\_\_(self): el constructor de la clase. Aquí es donde usualmente definiremos todos los elementos arquitéctonicos de nuestra red. Aquí definiremos que capas tendrá, qué funciones de activación, funciones de pooling, etc.

* Método forward(self, input): define las conexiones entre capas del modelo, o cómo debe fluir la información que entra en él. Debe retornar un tensor.

### Elementos arquitectónicos

Todos estos elementos están definidos en el paquete torch.nn (de Neural Networks). Todos derivan de la clase torch.nn.Module.

* **Linear:** capa lineal. Toma como parámetros las cantidades de neuronas de entrada y de salida.
* **Conv1d, Conv2d, Conv3d**: capas convolucionales de 1, 2 y 3 dimensiones respectivamente. Definidas por el tamaño del kernel que ocupan, el *stride*, filtros de entrada y de salida.
* **ReLU**: función de activación. No tiene parámetros.
* **Sigmoid**: función de activación. No tiene parámetros.
* **Softmax**: capa que transforma el output en una distribución de probabilidad. Parámetro es sobre la o las dimensiones que se aplica.
* **MaxPool1d, MaxPool2d, MaxPool3d**: Funciones de pooling en 1,2 y 3 dimensiones respectivamente.
* **Dropout**: capa que deja en 0 neuronas con probabilidad $p$. Parámetro: $p$.
* **BatchNorm2d**: capa que normaliza el input de acuerdo a una media y varianza aprendidas.
* **LayerNorm**:
* **Sequential**: es un agrupador de Módulos. Se encarga de que la información fluya de forma secuencial entre los módulos que contiene.

In [ ]:
import torch
from torch.nn import Linear, ReLU, Sigmoid, Sequential, Softmax, BatchNorm1d, BatchNorm2d, Dropout, LayerNorm

tensor_prueba = torch.randn((3, 5))

print(tensor_prueba, tensor_prueba.shape)

# Capa Lineal que va de 5 dimensiones a 8
capa_lineal = Linear(5, 8)
tensor_nuevo = capa_lineal(tensor_prueba)
print("Tensor después de Capa Lineal:")
print(tensor_nuevo, tensor_nuevo.shape)

tensor([[ 1.8557,  0.1690, -1.6810, -0.3846,  0.3428],
        [ 0.1939,  0.9907, -2.5539, -1.3668,  0.6404],
        [ 0.6933,  0.0300,  0.3220, -0.2189,  0.8146]]) torch.Size([3, 5])
Tensor después de Capa Lineal:
tensor([[-1.0699, -0.0591, -0.0866,  0.4900,  0.1225,  0.4351, -1.6752,  0.1189],
        [-1.3527, -0.5245, -0.6853, -0.3481,  0.4710,  0.5990, -1.5810,  1.1150],
        [-0.1476,  0.0925, -0.4386, -0.0050,  0.1056, -0.3807, -0.5575,  0.3178]],
       grad_fn=<AddmmBackward0>) torch.Size([3, 8])


In [ ]:
# Funciones de Activación
# ReLU
relu = ReLU()
print("Antes de ReLU: ")
print(tensor_prueba)
print("Después de ReLU: ")
print(relu(tensor_prueba))

Antes de ReLU: 
tensor([[ 1.8557,  0.1690, -1.6810, -0.3846,  0.3428],
        [ 0.1939,  0.9907, -2.5539, -1.3668,  0.6404],
        [ 0.6933,  0.0300,  0.3220, -0.2189,  0.8146]])
Después de ReLU: 
tensor([[1.8557, 0.1690, 0.0000, 0.0000, 0.3428],
        [0.1939, 0.9907, 0.0000, 0.0000, 0.6404],
        [0.6933, 0.0300, 0.3220, 0.0000, 0.8146]])


In [ ]:
# Sigmoid
s = Sigmoid()
print("Antes de Sigmoid: ")
print(tensor_prueba)
print("Después de Sigmoid: ")
print(s(tensor_prueba))

Antes de Sigmoid: 
tensor([[ 1.8557,  0.1690, -1.6810, -0.3846,  0.3428],
        [ 0.1939,  0.9907, -2.5539, -1.3668,  0.6404],
        [ 0.6933,  0.0300,  0.3220, -0.2189,  0.8146]])
Después de Sigmoid: 
tensor([[0.8648, 0.5421, 0.1570, 0.4050, 0.5849],
        [0.5483, 0.7292, 0.0722, 0.2031, 0.6548],
        [0.6667, 0.5075, 0.5798, 0.4455, 0.6931]])


In [ ]:
# Softmax
soft = Softmax(dim=1)
print("Antes de Softmax: ")
print(tensor_prueba)
print("Después de Softmax: ")
soft_tensor = soft(tensor_prueba)
print(soft_tensor)
print(soft_tensor.sum(dim=0))

Antes de Softmax: 
tensor([[ 1.8557,  0.1690, -1.6810, -0.3846,  0.3428],
        [ 0.1939,  0.9907, -2.5539, -1.3668,  0.6404],
        [ 0.6933,  0.0300,  0.3220, -0.2189,  0.8146]])
Después de Softmax: 
tensor([[0.6490, 0.1201, 0.0189, 0.0691, 0.1429],
        [0.1978, 0.4388, 0.0127, 0.0415, 0.3091],
        [0.2677, 0.1379, 0.1847, 0.1075, 0.3022]])
tensor([1.1145, 0.6969, 0.2162, 0.2181, 0.7543])


In [ ]:
# Sequential
# Unamos pasos
seq = Sequential(capa_lineal, relu, soft)
tensor_final = seq(tensor_prueba)
print("Aplicando Sequential: ")
print(tensor_final, tensor_final.shape)

Aplicando Sequential: 
tensor([[0.1060, 0.1060, 0.1060, 0.1730, 0.1198, 0.1638, 0.1060, 0.1194],
        [0.0872, 0.0872, 0.0872, 0.0872, 0.1396, 0.1587, 0.0872, 0.2658],
        [0.1165, 0.1278, 0.1165, 0.1165, 0.1295, 0.1165, 0.1165, 0.1601]],
       grad_fn=<SoftmaxBackward0>) torch.Size([3, 8])


In [ ]:
# Dropout
drop = Dropout(p=0.1) # con probabilidad de dejar en 0 de 0.5.

tensor_dropout = drop(tensor_prueba)
print(tensor_dropout)

tensor([[ 2.0619,  0.1878, -1.8678, -0.4273,  0.0000],
        [ 0.2155,  1.1008, -2.8377, -1.5187,  0.7115],
        [ 0.7703,  0.0334,  0.3577, -0.0000,  0.9051]])


In [ ]:
# Batch Normalization 1d
tensor_lineal = 100*torch.randn((3, 5))  # Una imagen con varianza alta
bn = BatchNorm1d(5, momentum=None)
print("La media de los vectores originales por dimensión es: {}".format(tensor_lineal.mean(dim=[0])))
print("La varianza de los vectores originales por dimensión es: {}".format(tensor_lineal.var(dim=[0], unbiased=False)))
print("Las medias por dimensión de BN inicialmente son: {}".format(bn.running_mean))
print("Las varianzas por dimensión de BN inicialmente son: {}".format(bn.running_var))

tensor_bn = bn(tensor_lineal)

print("La media por dimensión del resultado es: {}".format(tensor_bn.mean(dim=[0])))
print("La varianza por dimensión del resultado es: {}".format(tensor_bn.var(dim=[0], unbiased=False)))
print("Las medias por dimensión de BN ahora son: {}".format(bn.running_mean))
print("Las varianzas por dimensión de BN ahora son: {}".format(bn.running_var))

for n, p in bn.named_parameters():
    print(n,p)

La media de los vectores originales por dimensión es: tensor([ -10.5603, -126.0420,  101.3846,   15.9988,   54.4600])
La varianza de los vectores originales por dimensión es: tensor([ 3305.6323,  6955.5879, 24636.8613,  8743.3779,   918.1909])
Las medias por dimensión de BN inicialmente son: tensor([0., 0., 0., 0., 0.])
Las varianzas por dimensión de BN inicialmente son: tensor([1., 1., 1., 1., 1.])
La media por dimensión del resultado es: tensor([ 0.0000e+00,  4.4703e-08, -3.9736e-08,  0.0000e+00, -6.9539e-08],
       grad_fn=<MeanBackward1>)
La varianza por dimensión del resultado es: tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000], grad_fn=<VarBackward0>)
Las medias por dimensión de BN ahora son: tensor([ -10.5603, -126.0420,  101.3846,   15.9988,   54.4600])
Las varianzas por dimensión de BN ahora son: tensor([ 4958.4487, 10433.3818, 36955.2891, 13115.0664,  1377.2864])
weight Parameter containing:
tensor([1., 1., 1., 1., 1.], requires_grad=True)
bias Parameter containing:
tensor([

In [ ]:
# Batch Normalization 2d
tensor_imagenes = 20*torch.randn((4, 3, 2, 2))  # Una imagen con varianza alta
bn = BatchNorm2d(3, momentum = None, eps=0.0)                             # 3 es el número de canales


print("La media de las imágenes originales por canal es: {}".format(tensor_imagenes.mean(dim=[0,2,3])))
print("La varianza de las imágenes originales por canal es: {}".format(tensor_imagenes.var(dim=[0,2,3], unbiased=True)))
print("Las medias por canal de BN inicialmente son: {}".format(bn.running_mean))
print("Las varianzas por canal de BN inicialmente son: {}".format(bn.running_var))

tensor_bn = bn(tensor_imagenes)
print("La media por canal es: {}".format(tensor_bn.mean(dim=[0,2,3])))
print("La varianza por canal es: {}".format(tensor_bn.var(dim=[0,2,3], unbiased=True)))
print("Las medias por canal de BN ahora son: {}".format(bn.running_mean))
print("Las varianzas por canal de BN ahora son: {}".format(bn.running_var))

for n, p in bn.named_parameters():
    print(n,p)

La media de las imágenes originales por canal es: tensor([6.3272, 0.2542, 5.7548])
La varianza de las imágenes originales por canal es: tensor([136.9783, 460.3089, 490.1544])
Las medias por canal de BN inicialmente son: tensor([0., 0., 0.])
Las varianzas por canal de BN inicialmente son: tensor([1., 1., 1.])
La media por canal es: tensor([ 5.2154e-08, -1.4901e-08, -1.1176e-08], grad_fn=<MeanBackward1>)
La varianza por canal es: tensor([1.0667, 1.0667, 1.0667], grad_fn=<VarBackward0>)
Las medias por canal de BN ahora son: tensor([6.3272, 0.2542, 5.7548])
Las varianzas por canal de BN ahora son: tensor([136.9783, 460.3089, 490.1544])
weight Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
bias Parameter containing:
tensor([0., 0., 0.], requires_grad=True)


In [ ]:
# Layer Normalization
tensor_lineal = 100*torch.randn((20, 100))  # Una imagen con varianza alta
ln = LayerNorm(100, eps=0 ,elementwise_affine=True) # elementwise_affine determina si tiene parámetros aprendibles o no.
print("Media del resultado: ", ln(tensor_lineal).mean(dim=1))
print("Desviación estándar del resultado: ", ln(tensor_lineal).std(dim=1, unbiased=False))
for n, p in ln.named_parameters():
  print(n,p)

# Cambiemos la media y desviación estándar a mano
new_weight1 = torch.ones(100) * 100.0
new_weight2 = torch.ones(100) * 5.0
with torch.no_grad():
    ln.weight.copy_(new_weight1)
    ln.bias.copy_(new_weight2)

# evaluamos de nuevo sobre los mismos datos
print("Media del resultado: ", ln(tensor_lineal).mean(dim=1))
print("Desviación estándar del resultado: ", ln(tensor_lineal).std(dim=1, unbiased=False))

Media del resultado:  tensor([-3.5763e-09,  1.1921e-09,  8.3447e-09, -2.8610e-08,  7.1526e-09,
         2.6226e-08, -1.6689e-08, -4.7684e-09,  4.7684e-09, -2.3842e-08,
         9.5367e-09,  2.3842e-09,  2.3842e-08,  4.7684e-09,  0.0000e+00,
         4.7684e-09,  2.3842e-09,  2.3842e-09, -2.5332e-08,  0.0000e+00],
       grad_fn=<MeanBackward1>)
Desviación estándar del resultado:  tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000,
        1.0000, 1.0000], grad_fn=<StdBackward0>)
weight Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,

### Revisitando AlexNet

In [ ]:
import torch
import torch.nn as nn           # Esto es PyTorch y su módulo de Redes Neuronales

class MiAlexNet(nn.Module):               # Esta clase representa nuestro modelo

    def __init__(self):   # Constructor, aquí armamos las piezas de nuestra red
        super(MiAlexNet, self).__init__()
        # Bloques Convolucionales
        # Recordemos que los Bloques Convolucionales van a estar hechos de 3
        # elementos: Convolución, Pooling y Activación.
        # En este caso usaremos Convoluciones 2d, Max Pooling y ReLU


        # Input = 3x 224 x 224 Output = 96 x 55 x 55 --> Max Pool = 96 x 27 x 27
        self.conv1 = nn.Sequential(
            nn.Conv2d(                           # Todo esto define a la Convolución
                      in_channels=3,             # Filtros/Canales de Entrada (RGB)
                      out_channels=96,           # Filtros/Canales de Salida
                      kernel_size=(11,11),       # Tamaño de la Convolución
                      stride=(4,4),              # Stride
                      padding=2),                # Cuántos pixeles de padding
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)), # Max Pooling
            nn.ReLU()                            # Activación
        )

        # Input = 96 x 27 x 27 Output = 256 x 27 x 27 --> Max Pool = 256 x 13 x 13
        self.conv2 = nn.Sequential(
            nn.Conv2d(
                      in_channels=96,
                      out_channels=256,
                      kernel_size=(5,5),
                      stride=(1,1),
                      padding=2),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        # Input = 256 x 13 x 13 Output = 384 x 13 x 13
        self.conv3 = nn.Sequential(
            nn.Conv2d(
                      in_channels=256,
                      out_channels=384,
                      kernel_size=(3,3),
                      stride=(1,1),
                      padding=1),
            nn.ReLU()
        )
        # Input = 384 x 13 x 13 Output = 384 x 13 x 13
        self.conv4 = nn.Sequential(
            nn.Conv2d(
                      in_channels=384,
                      out_channels=384,
                      kernel_size=(3,3),
                      stride=(1,1),
                      padding=1),
            nn.ReLU()
        )
        # Input = 384 x 13 x 13 Output = 256 x 13 x 13 --> MaxPool = 256 x 6 x 6
        self.conv5 = nn.Sequential(
            nn.Conv2d(
                      in_channels=384,
                      out_channels=256,
                      kernel_size=(3,3),
                      stride=(1,1),
                      padding=1),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        ##
        self.flat = nn.Flatten()    # Capa aplanamiento para poder vincular
                                    # resultado convolucional con capas
                                    # lineales.

        # Bloques Fully Connected/MLP
        # Input = 256 x 6 x 6 = 9216 Output = 4096
        self.fc6 = nn.Sequential( #nn.Dropout(),
                                  nn.Linear(9216, 4096),
                                  nn.ReLU()
                                  )
        # Input = 4096 Output = 4096
        self.fc7 = nn.Sequential(  #nn.Dropout(),
                                  nn.Linear(4096, 4096),
                                  nn.ReLU()
                                  )
        # Input = 4096 Output = 1000
        self.fc8 = nn.Sequential(
                                  nn.Linear(4096, 102)
                                  )



    def forward(self, x):        # Aquí armamos cómo se conectan las piezas
                                 # Esta red es sencilla pues solo tenemos
                                 # que conectar las piezas una detrás de la
                                 # otra. No todas las redes son así.
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.conv4(x)
        x = self.conv5(x)
        x = self.flat(x)
        x = self.fc6(x)
        x = self.fc7(x)
        x = self.fc8(x)

        return x

In [ ]:
m = MiAlexNet()

In [ ]:
for n, p in m.named_parameters():
  print(n, p.shape)


conv1.0.weight torch.Size([96, 3, 11, 11])
conv1.0.bias torch.Size([96])
conv2.0.weight torch.Size([256, 96, 5, 5])
conv2.0.bias torch.Size([256])
conv3.0.weight torch.Size([384, 256, 3, 3])
conv3.0.bias torch.Size([384])
conv4.0.weight torch.Size([384, 384, 3, 3])
conv4.0.bias torch.Size([384])
conv5.0.weight torch.Size([256, 384, 3, 3])
conv5.0.bias torch.Size([256])
fc6.0.weight torch.Size([4096, 9216])
fc6.0.bias torch.Size([4096])
fc7.0.weight torch.Size([4096, 4096])
fc7.0.bias torch.Size([4096])
fc8.0.weight torch.Size([102, 4096])
fc8.0.bias torch.Size([102])


In [ ]:
fotos_de_mentira = torch.randn(15, 3, 224, 224)

m(fotos_de_mentira).shape

torch.Size([15, 102])

## Manejo de Datos

En un problema normal de Machine Learning, usualmente la gestión de datos no era muy importante dado que los datasets en general son pequeños. Sin embargo, dados los volúmenes de datos que requieren los modelos de aprendizaje profundo, se vuelve difícil mantener los datos en memoria. Por esto, se requiere consumirlos de manera parcelada para poder ocuparlos con las restricciones de hardware que tenemos.

Pytorch resuelve el problema mediante dos abstracciones: las clases *Dataset* y *DataLoader*.

* La clase *Dataset* trabaja como una interfaz sencilla para acceder nuestros datos físicos.
* La clase *DataLoader* se encarga de agrupar los elementos de la clase *Dataset* en *batches* para pasarle a nuestro modelo.

Usualmente, el mayor trabajo reside en definir una clase Dataset apropiada para nuestro conjunto de datos. Por suerte, si queremos trabajar con ciertos conjuntos de datos estándar, Pytorch ya tiene definido estos datasets por nosotros.

Si no, lo único que tenemos que hacer es definir una clase que herede de torch.utils.data.Dataset y que implemente dos métodos:

* \_\_len(self)\_\_: método que devuelva el tamaño total del dataset.
* \_\_getitem\_\_(self, index): método que entregue un elemento particular del dataset dado un índice (index).

### Usar Datasets predefinidos

In [ ]:
from torchvision.datasets import MNIST, CIFAR10

mnist_train = MNIST(root=".", train=True, download=True)
cifar = CIFAR10(root=".", train=True, download=True)

100%|██████████| 9.91M/9.91M [00:00<00:00, 14.1MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 339kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 3.19MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 15.2MB/s]
100%|██████████| 170M/170M [00:06<00:00, 27.8MB/s]


In [ ]:
len(mnist_train)

60000

Veamos un ejemplo del dataset.

In [ ]:
mnist_train[459]

(<PIL.Image.Image image mode=L size=28x28>, 3)

Vemos que contiene dos elementos: el primero es una imagen en formato PIL y el segundo es la clase asociada a esa imagen (nuestro target o ground truth). La imagen se ve así:

In [ ]:
from IPython.display import display     # Esto no es Pytorch, es solo una librería
                                        # para desplegar imágenes en Colab.
display(mnist_train[459][0])
#display(cifar[0][0])

Sin embargo, una imagen en formato PIL no es un tensor de Pytorch. Tenemos que hacer algo para transformarla! Por suerte para nosotros, Pytorch nos ofrece transformaciones estándar para imágenes, en particular, una para transformar imágenes PIL a tensores. Veamos cómo:

In [ ]:
from torchvision.transforms import ToTensor
mnist_train = MNIST(root=".", train=True, download=True, transform=ToTensor())

In [ ]:
mnist_train[459]

(tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 

Ahora nuestro Dataset automáticamente transforma las imágenes PIL a tensores de Pytorch!

### Crear un Dataset de ejemplo

Vamos a crear un Dataset para el conjunto de datos Flowers que vimos el laboratorio pasado.

In [ ]:
!wget https://www.dropbox.com/s/q53g4cmpnvzhnhi/flowers.tar.gz -q --show-progress
!tar -xzf flowers.tar.gz

flowers.tar.gz      100%[===================>] 328.99M  34.7MB/s    in 9.6s    


In [ ]:
from os import listdir
from os.path import join
from PIL import Image
import torch
from torchvision.transforms import Compose, ToTensor, Resize
class Flowers(torch.utils.data.Dataset):
    def __init__(self, root, transform=None):
        self.root = root
        self.transform = transform
        self.imagenes = []       # Vincula el indice con un nombre de archivo
        self.imgs_to_class = []  # Vincula el indice con una clase
        self.imagenes, self.imgs_to_class = self.armar_indices(root)

    def armar_indices(self, root):
        n_classes = len(listdir(root)) # El número de carpetas es la cantidad de clases
        contador = 0
        lista_imagenes = []
        imgs_to_class = []
        for clase in listdir(root):
            directorio = join(root, clase)
            for archivo in listdir(directorio):
                lista_imagenes.append(archivo)
                contador+=1
                imgs_to_class.append(int(clase))

        return lista_imagenes, imgs_to_class

    def obtener_imagen(self, archivo):

        im = Image.open(archivo)
        return im

    def __getitem__(self, idx):

        nombre_archivo = self.imagenes[idx]
        clase = self.imgs_to_class[idx]
        ruta_img = join(self.root, str(clase))
        ruta_img = join(ruta_img, nombre_archivo)
        img = self.obtener_imagen(ruta_img)

        if self.transform is not None:
            img = self.transform(img)
        return img, clase

    def __len__(self):
        return len(self.imagenes)

In [ ]:
transforms = Compose([Resize((224,224)), ToTensor()])
f = Flowers('flowers_dataset/train', transform=transforms)
print(f[0])

(tensor([[[0.1961, 0.2078, 0.2157,  ..., 0.3020, 0.2863, 0.2706],
         [0.2039, 0.2196, 0.2353,  ..., 0.3059, 0.2863, 0.2784],
         [0.2039, 0.2157, 0.2275,  ..., 0.3059, 0.2902, 0.2824],
         ...,
         [0.5294, 0.4471, 0.3294,  ..., 0.3961, 0.4078, 0.3922],
         [0.5882, 0.5451, 0.4471,  ..., 0.3647, 0.3490, 0.3294],
         [0.5922, 0.5608, 0.4980,  ..., 0.3490, 0.3412, 0.3294]],

        [[0.2510, 0.2431, 0.2314,  ..., 0.3569, 0.3725, 0.3804],
         [0.2549, 0.2471, 0.2510,  ..., 0.3608, 0.3725, 0.3843],
         [0.2471, 0.2392, 0.2353,  ..., 0.3686, 0.3804, 0.3843],
         ...,
         [0.5294, 0.4627, 0.3647,  ..., 0.3961, 0.4118, 0.3961],
         [0.5569, 0.5176, 0.4353,  ..., 0.3882, 0.3922, 0.3843],
         [0.5529, 0.5294, 0.4824,  ..., 0.3725, 0.3922, 0.3882]],

        [[0.1412, 0.1412, 0.1373,  ..., 0.2353, 0.2235, 0.2196],
         [0.1529, 0.1529, 0.1608,  ..., 0.2392, 0.2235, 0.2275],
         [0.1490, 0.1490, 0.1529,  ..., 0.2314, 0.2314, 0

In [ ]:
len(f)

5687

### Iterar sobre los datos

Dado un Dataset, sea hecho por nosotros o uno predefinido, iterar sobre los datos es muy sencillo. Simplemente tenemos que crear un objeto DataLoader que toma como argumento el Dataset y definir el batch size con que queremos trabajar.


Este código iterará por todos los batches de ejemplos de nuestro dataset y parará cuando se acaben. Es decir, esto corre por una **época**.

In [ ]:
from torch.utils.data import DataLoader
train_dl = DataLoader(f, batch_size=128, shuffle=True)

for n_batch, (x, target) in enumerate(train_dl):
    print("\rN_Batch: {} input: {}- Label:{}".format(n_batch, x.shape, target.shape), end="")

N_Batch: 44 input: torch.Size([55, 3, 224, 224])- Label:torch.Size([55])

### Optimización

¿Como obtenemos los pesos óptimos para nuestra red? Si recordamos nuestras clases anteriores debemos optimizar la función de pérdida para tratar de encontrar los parámetros de nuestra red que minimizan su valor.

Primero debemos definir la función de pérdida. Éstas están definidas en torch.nn también. Las usuales son:

* CrossEntropyLoss: Entropía Cruzada, mide la distancia entre dos distribuciones de probabilidad. La función de pérdida más común para problemas de clasificación.
* MSELoss: Error cuadrático medio. Pérdida usual en problemas de regresión.

Hay más para revisar en la documentación de Pytorch (https://pytorch.org/docs/stable/nn.html).

Dado el resultado de nuestra red y el ground truth que deberíamos predecir, la pérdida es:


In [ ]:
from torch.nn import CrossEntropyLoss
funcion_perdida = CrossEntropyLoss()

In [ ]:
loss = funcion_perdida(output, target) # No correr este código, va a dar error! Es un ejemplo!

NameError: name 'output' is not defined

Súper, tenemos la pérdida, ¿cómo calculamos los gradientes?

Para eso necesitamos un algoritmo de optimización. En el curso de Herramientas verán los algoritmos en detalle, pero les debería sonar Stochastic Gradient Descent (SGD), que es el algoritmo estándar de optimización. Este ya está implementado por el paquete torch.optim.


In [ ]:
from torch.optim import SGD, Adam

optimizer = SGD(model.parameters())     # Vinculamos el recién creado optimizador
                                        # a los parámetros de nuestro modelo

Esto por sí solo todavía no hace nada. El optimizador va a ir gestionando los gradientes que le llegan a cada parámetro de nuestro modelo. Actualizará los valores de los parámetros de acuerdo al algoritmo de optimización que implemente.

Pero para gestionar gradientes tiene que sacarlos de alguna parte. ¡Esto lo hace backpropagation! Por suerte es muy fácil calcularlos en Pytorch.

In [ ]:
loss.backward()                         # ¡Backpropagation! Eso es todo.

Luego uniendo todas las piezas, en cada iteración de nuestro algoritmo de entrenamiento haremos lo siguiente:

In [ ]:
optimizer.zero_grad()                   # 1. Hacemos cero los gradientes de los parámetros
output = model(input)                   # 2. Propagamos los datos de entrada por nuestro modelo
loss = funcion_perdida(output, target)  # 3. Cálculamos la pérdida
loss.backward()                         # 4. ¡Backpropagation! Calculamos los gradientes
                                        # para nuestros parámetros. ¡Los gradientes
                                        # dejan de ser 0!
optimizer.step()                        # 5. Actualizamos los parámetros de nuestro modelo

## Evaluación de Rendimiento

¿Cómo evaluamos el rendimiento? En problemas de clasificación lo que usualmente haremos es comparar el ground truth respecto a lo que predecimos. ¿Qué es lo que predecimos? Usualmente será la clase de mayor valor en su salida entre las N clases que tenemos que predecir. Esto lo podemos hacer usando la función *argmax* de Pytorch.

In [ ]:
output = model(input)                       # Tensor de salida de tamaño (batch_size, n_clases)
preds = output.argmax(dim=1)                # Nos quedamos con el índice que tiene mayor valor
                                            # entre las N clases.
n_correctas = (preds == targets).sum()      # preds == targets entrega un tensor de 1s o 0s.
total = targets.shape[0]                    # Total de ejemplos
acc = n_correctas/total                     # Accuracy es correctas/total

## Uniendo todo

Vamos a unir todos estos componentes para armar un flujo de entrenamiento completo:

In [ ]:
import torch
import torch.nn as nn           # Esto es PyTorch y su módulo de Redes Neuronales

class MiAlexNet(nn.Module):               # Esta clase representa nuestro modelo

    def __init__(self):   # Constructor, aquí armamos las piezas de nuestra red
        super(MiAlexNet, self).__init__()
        # Bloques Convolucionales
        # Recordemos que los Bloques Convolucionales van a estar hechos de 3
        # elementos: Convolución, Pooling y Activación.
        # En este caso usaremos Convoluciones 2d, Max Pooling y ReLU


        # Input = 3x 224 x 224 Output = 96 x 55 x 55 --> Max Pool = 96 x 27 x 27
        self.conv1 = nn.Sequential(
            nn.Conv2d(                           # Todo esto define a la Convolución
                      in_channels=3,             # Filtros/Canales de Entrada (RGB)
                      out_channels=96,           # Filtros/Canales de Salida
                      kernel_size=(11,11),       # Tamaño de la Convolución
                      stride=(4,4),              # Stride
                      padding=2),                # Cuántos pixeles de padding
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)), # Max Pooling
            nn.ReLU()                            # Activación
        )

        # Input = 96 x 27 x 27 Output = 256 x 27 x 27 --> Max Pool = 256 x 13 x 13
        self.conv2 = nn.Sequential(
            nn.Conv2d(
                      in_channels=96,
                      out_channels=256,
                      kernel_size=(5,5),
                      stride=(1,1),
                      padding=2),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        # Input = 256 x 13 x 13 Output = 384 x 13 x 13
        self.conv3 = nn.Sequential(
            nn.Conv2d(
                      in_channels=256,
                      out_channels=384,
                      kernel_size=(3,3),
                      stride=(1,1),
                      padding=1),
            nn.ReLU()
        )
        # Input = 384 x 13 x 13 Output = 384 x 13 x 13
        self.conv4 = nn.Sequential(
            nn.Conv2d(
                      in_channels=384,
                      out_channels=384,
                      kernel_size=(3,3),
                      stride=(1,1),
                      padding=1),
            nn.ReLU()
        )
        # Input = 384 x 13 x 13 Output = 256 x 13 x 13 --> MaxPool = 256 x 6 x 6
        self.conv5 = nn.Sequential(
            nn.Conv2d(
                      in_channels=384,
                      out_channels=256,
                      kernel_size=(3,3),
                      stride=(1,1),
                      padding=1),
            nn.MaxPool2d(kernel_size=(3,3), stride=(2,2)),
            nn.ReLU()
        )
        ##
        self.flat = nn.Flatten()    # Capa aplanamiento para poder vincular
                                    # resultado convolucional con capas
                                    # lineales.

        # Bloques Fully Connected/MLP
        # Input = 256 x 6 x 6 = 9216 Output = 4096
        self.fc6 = nn.Sequential( #nn.Dropout(),
                                  nn.Linear(9216, 4096),
                                  nn.ReLU()
                                  )
        # Input = 4096 Output = 4096
        self.fc7 = nn.Sequential(  #nn.Dropout(),
                                  nn.Linear(4096, 4096),
                                  nn.ReLU()
                                  )
        # Input = 4096 Output = 1000
        self.fc8 = nn.Sequential(
                                  nn.Linear(4096, 102)
                                  )


    def forward(self, x):        # Aquí armamos cómo se conectan las piezas
                                 # Esta red es sencilla pues solo tenemos
                                 # que conectar las piezas una detrás de la
                                 # otra. No todas las redes son así.
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.conv4(x)
        x = self.conv5(x)
        x = self.flat(x)
        x = self.fc6(x)
        x = self.fc7(x)
        x = self.fc8(x)

        return x

In [ ]:
from torch.utils.data import DataLoader
from torch.optim import Adam
from torch.nn import CrossEntropyLoss
from torchvision.models import alexnet

model = MiAlexNet()
#Descomentar esto para ocupar modelo preentrenado
#model = alexnet(pretrained=True)
#model.features.requires_grad_(False)
#model.classifier = nn.Sequential(
#            nn.Dropout(),
#            nn.Linear(256 * 6 * 6, 4096),
#            nn.ReLU(inplace=True),
#            nn.Dropout(),
#            nn.Linear(4096, 4096),
#            nn.ReLU(inplace=True),
#            nn.Linear(4096, 102),
#        )

model = model.cuda()    # Lo enviamos para que se ejecute en GPU
transforms = Compose([Resize((224, 224)), ToTensor()])
ds_train = Flowers("flowers_dataset/train", transform=transforms) # Creamos

n_epochs = 10
train_dl = DataLoader(ds_train, batch_size=128, shuffle=True)

optimizer = Adam(model.parameters(), lr=0.001)    # Creamos nuestro optimizador
loss_function = CrossEntropyLoss()      # Creamos la función de pérdida

model.train()                           # Dejamos el modelo en modo de entrenamiento
for epoch in range(1, n_epochs + 1):
    total_correctas = 0.0
    total_muestras = 0.0

    for x, target in train_dl:          # Iteramos sobre nuestros datos
        # Inicio de la iteración
        optimizer.zero_grad()           # Hacemos cero los gradientes de nuestros parámetros
        x = x.cuda()
        target = target.cuda()          # Enviamos nuestros datos a GPU
        output = model(x)               # Hacemos el forward de nuestros datos

        loss = loss_function(output, target)     # Calculamos la pérdida
        loss.backward()                          # Backpropagation
        optimizer.step()                         # Actualizamos parámetros

        preds = output.argmax(dim=1)             # El máximo valor es nuestra predicción
        correctas = (preds == target).sum()      # Acumulamos las correctas durante la época
        total_correctas += correctas
        total_muestras += target.shape[0]        # Sumamos el tamaño del batch

        accuracy = total_correctas/total_muestras # Acc = correctas/total

        print("\rEpoca {}: Loss: {:.2f} Correctas: {} Total: {} Accuracy: {:.2f}%".format(epoch,
                                                                                      loss,
                                                                                      total_correctas,
                                                                                      total_muestras,
                                                                                      100*accuracy), end="")
    print("")

Epoca 1: Loss: 4.44 Correctas: 135.0 Total: 5687.0 Accuracy: 2.37%
Epoca 2: Loss: 4.06 Correctas: 267.0 Total: 5687.0 Accuracy: 4.69%
Epoca 3: Loss: 3.76 Correctas: 382.0 Total: 5687.0 Accuracy: 6.72%
Epoca 4: Loss: 3.61 Correctas: 422.0 Total: 5687.0 Accuracy: 7.42%
Epoca 5: Loss: 3.64 Correctas: 635.0 Total: 5687.0 Accuracy: 11.17%
Epoca 6: Loss: 3.43 Correctas: 730.0 Total: 5687.0 Accuracy: 12.84%
Epoca 7: Loss: 3.31 Correctas: 928.0 Total: 5687.0 Accuracy: 16.32%
Epoca 8: Loss: 3.08 Correctas: 1047.0 Total: 5687.0 Accuracy: 18.41%
Epoca 9: Loss: 3.25 Correctas: 1179.0 Total: 5687.0 Accuracy: 20.73%
Epoca 10: Loss: 2.94 Correctas: 1291.0 Total: 5687.0 Accuracy: 22.70%


### Evaluando el modelo en el conjunto de Test

In [ ]:
from torch.utils.data import DataLoader
from torch.optim import Adam
from torch.nn import CrossEntropyLoss
from torchvision.models import alexnet
ds_test = Flowers("flowers_dataset/test", transform=transforms)
test_dl = DataLoader(ds_test, batch_size=1024)

total_correctas = 0.0
total_muestras = 0.0

model.eval()
for x, target in test_dl:          # Iteramos sobre nuestros datos
    # Inicio de la iteración
                      # Dejamos el modelo en modo evaluación
    with torch.no_grad():               # No se calculará información de gradientes
                                        # en el código de más abajo.
        x = x.cuda()
        target = target.cuda()          # Enviamos nuestros datos a GPU
        output = model(x)               # Hacemos el forward de nuestros datos

        loss = loss_function(output, target)     # Calculamos la pérdida

        preds = output.argmax(dim=1)             # El máximo valor es nuestra predicción
        correctas = (preds == target).sum()      # Acumulamos las correctas durante la época
        total_correctas += correctas
        total_muestras += target.shape[0]        # Sumamos el tamaño del batch

        accuracy = total_correctas/total_muestras # Acc = correctas/total

        print("\rLoss: {:.2f} Correctas: {} Total: {} Accuracy: {:.2f}%".format(loss,
                                                                                total_correctas,
                                                                                total_muestras,
                                                                                100*accuracy), end="")

Loss: 3.15 Correctas: 379.0 Total: 1738.0 Accuracy: 21.81%

## Guardar el Modelo

Una vez entrenado, querremos guardar el modelo para no tener que reentrenarlo cada vez que lo queramos usar. Esto es fácil de hacer en Pytorch.

La forma más eficiente y correcta es simplemente guardar los pesos. Estos se encuentran en una estructura llamada *'state_dict'* en el modelo. Una vez guardados, para recuperar nuestro modelo, tenemos que crear un modelo nuevo y ocupar el método *'load_state_dict'* para cargar los pesos.

In [ ]:
torch.save(model.state_dict(), "MNIST/pesos_modelo_entrenado.pth") # Guardamos a disco los pesos

modelo = MiAlexNet()                                # Modelo con pesos aleatorios
pesos = torch.load("MNIST/pesos_modelo_entrenado.pth") # Cargamos los pesos a una variable
modelo.load_state_dict(pesos)                       # ¡Los pesos se encuentran
                                                    # cargados en el modelo!

<All keys matched successfully>

## Actividades

1. Entrene el modelo MiAlexNet por 10 épocas. ¿Qué resultados obtiene en train y test?
2. Modifique el modelo MiAlexNet para que haya una capa de Dropout antes de FC6 y FC7. Entrénelo por 10 épocas. ¿Ve cambios en el rendimiento del modelo?
3. Agregue capas de Batch Normalization (*BatchNorm2d*) antes de Conv3, Conv4 y Conv5. Entrene el modelo por 10 épocas. ¿Ve algún cambio en el entrenamiento?
4. Ocupe el modelo preentrenado en ImageNet de AlexNet. Entrénelo por 10 épocas. ¿Afecta en algo en rendimiento? Para ocupar el modelo preentrenado reemplace esta línea del código de entrenamiento:

In [ ]:
model = MiAlexNet()     # Creamos el modelo

Por estas otras líneas:

In [ ]:
from torchvision.models import alexnet

model = alexnet(pretrained=True)
model.features.requires_grad_(False)
model.classifier = nn.Sequential(
            nn.Dropout(),
            nn.Linear(256 * 6 * 6, 4096),
            nn.ReLU(inplace=True),
            nn.Dropout(),
            nn.Linear(4096, 4096),
            nn.ReLU(inplace=True),
            nn.Linear(4096, 102),
        )

### Respuestas Actividad

Por favor, sus respuestas a la actividad acá. No modificar el código anterior.

**Actividad 1**

In [ ]:
# Ponga su código aquí

**Actividad 2**

In [ ]:
# Ponga su código aquí

**Actividad 3**

In [ ]:
# Ponga su código aquí

Actividad 4

In [ ]:
# Ponga su código aquí